
services:

  # application service
  app:
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db/youtube
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db

  # database service
  mongo_db:
      image: mongo
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      networks:
        - custom
networks:
  custom:
    driver: bridge