COMMENTS_SIZE = 7
GET_ANALYSIS_OF_TIME = 8
GET_ANALYSIS_OF_LANGUAGES = 9
GET_ANALYSIS_OF_EMOTION = 10
GET_ANALYSIS_OF_LIKES_VS_REPLIES = 11
GET_ANALYSIS_OF_NEQ_POS = 12
GET_POPULARITY = 13
GET_WORD_MAP = 14
