# Generated by Django 4.2.11 on 2024-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_requesttype_video_yt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='yt_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='yt_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
