# Generated by Django 4.2.11 on 2024-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_channel_yt_id_comment_yt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
