# Generated by Django 4.2.11 on 2024-05-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_request_date_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='yt_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='MainApp.video', to_field='yt_id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='yt_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='video', to='MainApp.channel', to_field='yt_id'),
        ),
    ]
