# Generated by Django 4.2.11 on 2024-05-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_channel_yt_id_alter_comment_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='custom_url',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videogroup',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='video_group', to='MainApp.video'),
        ),
    ]
