# Generated by Django 4.2.11 on 2024-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_channel_custom_url_alter_videogroup_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='yt_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channelgroup',
            name='channel',
            field=models.ManyToManyField(blank=True, related_name='channel_group', to='MainApp.channel'),
        ),
    ]
