# Generated by Django 4.2.11 on 2024-05-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_calculationresult_yt_id_alter_channelgroup_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='MainApp.requesttype'),
            preserve_default=False,
        ),
    ]
