# Generated by Django 4.2.11 on 2024-05-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_calculationresult_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
