# Generated by Django 4.2.11 on 2024-12-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emotions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
